require "bundler/gem_tasks"
require 'rspec/core/rake_task'


desc "build .gem into the pkg directory"
task :build do
	sh "gem build bib.gemspec"
end

desc "build and install .gem into system gems"
task :install do
	sh "gem install bib.gem"
end

desc "build and push .gem to Rubygems"
task :release do
	sh "gem push bib.gem"
end

desc "Run RSpec code examples"
RSpec::Core::RakeTask.new

task :default => :spec
